<?php

$title = 'Add new vacation request';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('vacation', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('type'));
echo $this->formRow($form->get('hours'));
echo $this->formRow($form->get('day'));
echo $this->formRow($form->get('month'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();