<div class="row">
    <div class="col-lg-8 col-lg-offset-2 centered">
        <img class="icon-flag logo-icon" src="/img/vacation_fun-30-512.png">
        <h1>Anno <?php echo $year ?></h1>
        <p>Ferie godute: <?php echo $goneVacationsHours ?> ore (<?php echo $goneVacationsDays ?> giorni)</p>
        <p>Permessi goduti: <?php echo $goneRolsHours ?> ore (<?php echo $goneRolsDays ?> giorni)</p>
        </br>
        <p>Ferie mancanti: <?php echo $vacationResidualHours ?> ore (<?php echo $vacationResidualDays ?> giorni)</p>
        <p>Permessi mancanti: <?php echo $rolResidualHours ?> ore (<?php echo $rolResidualDays ?> giorni)</p>
        </br>
        <p>Ore totali residue: <?php echo $totHoursResidual ?></p>
        <p>Giorni totali residui: <?php echo $totDaysResidual ?></p>

    </div><!-- /col-lg-8 -->
</div><!-- /row -->
