<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron" xmlns="http://www.w3.org/1999/html">
    <h1>Anno <?php echo $year ?></h1>
    <p>Ferie godute: <?php echo $goneVacationsHours ?> ore (<?php echo $goneVacationsDays ?> giorni)</p>
    <p>Permessi goduti: <?php echo $goneRolsHours ?> ore (<?php echo $goneRolsDays ?> giorni)</p>
    </br>
    <p>Ferie mancanti: <?php echo $vacationResidualHours ?> ore (<?php echo $vacationResidualDays ?> giorni)</p>
    <p>Permessi mancanti: <?php echo $rolResidualHours ?> ore (<?php echo $rolResidualDays ?> giorni)</p>
    </br>
    <p>Ore totali residue: <?php echo $totHoursResidual ?></p>
    <p>Giorni totali residui: <?php echo $totDaysResidual ?></p>
    </br>
</div>

